modLoader="javafml"
loaderVersion="[46,)"
license="MIT"

[[mods]]
    issueTrackerURL="https://github.com/BlakeBr0/MoreBuckets/issues"
    modId="morebuckets"
    version="${file.jarVersion}"
    displayName="More Buckets"
    displayURL="https://blakesmods.com/more-buckets"
    # logoFile="examplemod.png"
    authors="BlakeBr0"
    credits="thorgot"
    description='''
    Adds a bunch of new buckets.
    '''

    [[dependencies.morebuckets]]
        modId="forge"
        mandatory=true
        versionRange="[46.0.0,)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.morebuckets]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.19,3]"
        ordering="NONE"
        side="BOTH"
    [[dependencies.morebuckets]]
        modId="cucumber"
        mandatory=true
        versionRange="[6.1.0,)"
        ordering="NONE"
        side="BOTH"